#!/bin/bash

PRE=""
DIST="UNKNOWN"
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DIST=$NAME
fi

if [ "$DIST" == "Amazon Linux AMI" ]; then
    PRE="sudo "
    export DISPLAY=:0
fi

if [ ! -e cache ]; then
    mkdir cache
fi

if [ ! -e fonts ]; then
    ln -s tangram-es/scenes/fonts .
fi

$PRE npm start

# while true; do
#   sleep 1000
#   $PRE npm start
# done