#!/bin/bash

PRE=""
DIST="DARWIN"
PORT=8080
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DIST=$NAME
    PORT=80
fi

if [ "$DIST" == "Amazon Linux AMI" ]; then
    PRE="sudo "
    export DISPLAY=:0
fi

if [ ! -e cache ]; then
    mkdir cache
fi

$PRE npm start $PORT

# while true; do
#   sleep 1000
#   $PRE npm start
# done