#!/bin/bash

PRE=""
DIST="UNKNOWN"
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DIST=$NAME
fi

if [ "$DIST" == "Amazon Linux AMI" ]; then
    PRE="sudo "
fi

if [ ! -e cache ]; then
    mkdir cache
fi

if [ ! -e fonts ]; then
    ln -s build/bin/fonts .
fi

if [ ! -e scene.yaml ]; then
    ln -s build/bin/scene.yaml .
fi

npm install

$PRE npm start

# while true; do
#   sleep 1000
#   $PRE npm start
# done